#!/bin/bash
# Claude Code hook script — forwards all hook events to the companion server.
# For PreToolUse and Stop: blocks until server responds (mobile approval / message).
# For all others: fire-and-forget.
# Fails gracefully if server is down (default approve / continue).

INPUT=$(cat)
EVENT=$(echo "$INPUT" | grep -o '"hook_event_name":"[^"]*"' | cut -d'"' -f4)
PORT="${COMPANION_PORT:-3099}"
PIN="${COMPANION_PIN:-}"
URL="http://localhost:${PORT}/api/hooks/event"

# Auto-read PIN from token file (generated by server on first run)
if [ -z "$PIN" ]; then
  TOKEN_FILE="$HOME/.claude-companion-token"
  if [ -f "$TOKEN_FILE" ]; then
    PIN=$(cat "$TOKEN_FILE")
  fi
fi

# If still no PIN, skip silently (server not set up)
if [ -z "$PIN" ]; then
  echo '{}'
  exit 0
fi

case "$EVENT" in
  PreToolUse|Stop)
    # Blocking — wait for server response (up to 5 min)
    RESPONSE=$(curl -s --fail --max-time 300 \
      -X POST "$URL" \
      -H "Content-Type: application/json" \
      -H "X-Pin: $PIN" \
      -d "$INPUT" 2>/dev/null)
    if [ $? -ne 0 ] || [ -z "$RESPONSE" ]; then
      # Server down or error — default approve / continue
      if [ "$EVENT" = "PreToolUse" ]; then
        RESPONSE='{"decision":"approve"}'
      else
        RESPONSE='{}'
      fi
    fi
    ;;
  *)
    # Fire-and-forget
    curl -s --max-time 5 -X POST "$URL" \
      -H "Content-Type: application/json" \
      -H "X-Pin: $PIN" \
      -d "$INPUT" >/dev/null 2>&1 &
    RESPONSE='{}'
    ;;
esac

echo "$RESPONSE"
